export const products = [
  {
    id: 1,
    name: "Sandalia Kappa",
    category: "calzado",
    categoryLabel: "Sandalias · Kappa",
    details: "Tallas 43 · 44 · 45",
    sizes: ["43", "44", "45"],
    price: 40,
    oldPrice: null,
    tag: "Solo por hoy",
    tagClass: "tag-sale",
    note: "Pago completo",
    tone: "#c7c9c8",
    image: "assets/sandalia-kappa.jpeg"
  },
  {
    id: 2,
    name: "Polo Jordan",
    category: "ropa",
    categoryLabel: "Polo · Jordan",
    details: "Talla M",
    sizes: ["M"],
    price: 130,
    oldPrice: null,
    tag: "Original",
    note: "Separa con S/ 40 · llega en 10 días",
    tone: "#b8d0e9",
    image: "assets/polo-jordan.jpeg"
  },
  {
    id: 3,
    name: "Gorra BMW",
    category: "accesorios",
    categoryLabel: "Gorra · BMW",
    details: "Talla unica",
    sizes: [],
    price: 65,
    oldPrice: null,
    tag: "Original",
    tone: "#ded3bf",
    image: "assets/gorra-1.jpeg"
  },
  {
    id: 4,
    name: "Gorra Guess",
    category: "accesorios",
    categoryLabel: "Gorra · Guess",
    details: "",
    sizes: [],
    price: 135,
    oldPrice: null,
    tag: "Original",
    tone: "#aaa0ec",
    image: "assets/gorra-guess.jpeg"
  },
  {
    id: 5,
    name: "Polo Nike",
    category: "ropa",
    categoryLabel: "Polo · Nike",
    details: "Tallas M · L",
    sizes: ["M", "L"],
    price: 89,
    oldPrice: null,
    tag: "Original",
    tone: "#f0a08b",
    image: "assets/polo-nike.jpeg"
  },
  {
    id: 6,
    name: "Puma Suede XL",
    category: "calzado",
    categoryLabel: "Zapatillas · Puma",
    details: "Tallas 40.5 · 41 · 42 · 42.5 · 44.5",
    sizes: ["40.5", "41", "42", "42.5", "44.5"],
    price: 235,
    oldPrice: null,
    tag: "Original",
    tone: "#cee480",
    image: "assets/puma-suede-xl.jpeg"
  },
  {
    id: 7,
    name: "Puma Ferrari CA Match",
    category: "calzado",
    categoryLabel: "Zapatillas · Puma Ferrari",
    details: "Tallas 42 · 42.5 · 44.5",
    sizes: ["42", "42.5", "44.5"],
    price: 175,
    oldPrice: null,
    tag: "Original",
    tone: "#efb09c",
    image: "assets/puma-ferrari-ca-match.jpeg"
  },
  {
    id: 8,
    name: "Polo Puma",
    category: "ropa",
    categoryLabel: "Polo · Puma",
    details: "Tallas S · M · L · XL",
    sizes: ["S", "M", "L", "XL"],
    price: 59,
    oldPrice: null,
    tag: "Original",
    tone: "#a9caff",
    image: "assets/polo-puma-nuevo.jpeg"
  },
  {
    id: 9,
    name: "Camisero Puma BMW",
    category: "ropa",
    categoryLabel: "Camisero · Puma BMW",
    details: "Talla M",
    sizes: ["M"],
    price: 100,
    oldPrice: null,
    tag: "Solo quedan 2",
    tagClass: "tag-sale",
    note: "Stock limitado",
    tone: "#b8b9bd",
    image: "assets/camisero-puma-bmw.jpeg"
  },
  {
    id: 10,
    name: "Nike Air Max SC",
    category: "calzado",
    categoryLabel: "Zapatillas · Nike",
    details: "Tallas 40.5 · 41 · 42 · 42.5 · 43 · 44 · 44.5",
    sizes: ["40.5", "41", "42", "42.5", "43", "44", "44.5"],
    price: 239,
    oldPrice: null,
    tag: "Original",
    tone: "#f0a08b",
    image: "assets/nike-air-max-sc.jpeg"
  },
  {
    id: 11,
    name: "Sandalia Victori One",
    category: "calzado",
    categoryLabel: "Sandalias · Victori One",
    details: "Talla 39",
    sizes: ["39"],
    price: 85,
    oldPrice: null,
    tag: "Original",
    tone: "#d7d7d2",
    image: "assets/sandalias-1.jpeg"
  },
  {
    id: 12,
    name: "Nike Ebernon Low",
    category: "calzado",
    categoryLabel: "Zapatillas · Nike",
    details: "Tallas 41 · 42 · 42.5 · 43 · 44 · 44.5 · 45",
    sizes: ["41", "42", "42.5", "43", "44", "44.5", "45"],
    price: 189,
    oldPrice: null,
    tag: "Original",
    tone: "#ded3bf",
    image: "assets/nike-ebernon-low.jpeg"
  },
  {
    id: 13,
    name: "Polo Guess",
    category: "ropa",
    categoryLabel: "Polo · Guess",
    details: "Talla S",
    sizes: ["S"],
    price: 100,
    oldPrice: null,
    tag: "Original",
    tone: "#d0b5d8",
    image: "assets/polo-guess-nuevo.jpeg"
  },
  {
    id: 14,
    name: "Cartera Guess",
    category: "accesorios",
    categoryLabel: "Cartera - Guess",
    details: "Talla unica",
    sizes: [],
    price: 259,
    oldPrice: null,
    tag: "Original",
    tone: "#d5c3a7",
    image: "assets/cartera-guess.jpeg"
  },
  {
    id: 15,
    name: "Sandalia Calvin Klein",
    category: "calzado",
    categoryLabel: "Sandalias - Calvin Klein",
    details: "Talla 40",
    sizes: ["40"],
    price: 115,
    oldPrice: null,
    tag: "Sin box",
    tagClass: "tag-sale",
    note: "Sin caja",
    tone: "#d6d2ca",
    image: "assets/sandalias-calvin-klein.jpeg"
  },
  {
    id: 16,
    name: "Polera Puma",
    category: "ropa",
    categoryLabel: "Polera - Puma",
    details: "Tallas S - M",
    sizes: ["S", "M"],
    price: 99,
    oldPrice: null,
    tag: "Original",
    tone: "#b8c6b5",
    image: "assets/polera-puma.jpeg"
  },
  {
    id: 17,
    name: "Polo Tommy Hilfiger",
    category: "ropa",
    categoryLabel: "Polo - Tommy Hilfiger",
    details: "Talla M",
    sizes: ["M"],
    price: 125,
    oldPrice: null,
    tag: "Original",
    tone: "#d9c7b2",
    image: "assets/polo-tommy-hilfiger-nuevo.jpeg"
  },
  {
    id: 18,
    name: "Sandalia Nike Kobe Offcourt",
    category: "calzado",
    categoryLabel: "Sandalias - Nike",
    details: "Talla 42.5",
    sizes: ["42.5"],
    price: 149,
    oldPrice: null,
    tag: "Original",
    tone: "#d5d8dc",
    image: "assets/sandalias-nike.jpeg"
  },
  {
    id: 19,
    name: "Sandalia Puma",
    category: "calzado",
    categoryLabel: "Sandalias - Puma",
    details: "Talla 40.5",
    sizes: ["40.5"],
    price: 69,
    oldPrice: null,
    tag: "Preciazoo",
    tagClass: "tag-sale",
    tone: "#c5c2ba",
    image: "assets/sandalia-puma.jpeg"
  },
  {
    id: 20,
    name: "Polo",
    category: "ropa",
    categoryLabel: "Polo",
    details: "Talla S",
    sizes: ["S"],
    price: 69,
    oldPrice: null,
    tag: "Original",
    tone: "#c9c9c9",
    image: "assets/polo-4.jpeg"
  },
  {
    id: 21,
    name: "Polo Nike",
    category: "ropa",
    categoryLabel: "Polo · Nike",
    details: "Tallas S · M · XL",
    sizes: ["S", "M", "XL"],
    price: 90,
    oldPrice: null,
    tag: "Original",
    tone: "#bfc3c4",
    image: "assets/polo-nike-negro.jpeg"
  },
  {
    id: 22,
    name: "Sandalia",
    category: "calzado",
    categoryLabel: "Sandalias",
    details: "Talla 40",
    sizes: ["40"],
    price: 85,
    oldPrice: null,
    tag: "Original",
    tone: "#b9c0c6",
    image: "assets/sandalias-2.jpeg"
  },
  {
    id: 23,
    name: "Zapatillas Nike",
    category: "calzado",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla 40",
    sizes: ["40"],
    price: 415,
    oldPrice: null,
    tag: "Caja cortada",
    tagClass: "tag-sale",
    note: "Caja cortada",
    tone: "#d7dbe0",
    image: "assets/zapatillas-nike.jpeg"
  },
  {
    id: 24,
    name: "Zapatillas Nike Air",
    category: "calzado",
    categoryLabel: "Zapatillas · Nike",
    details: "Tallas 39 · 40 · 41",
    sizes: ["39", "40", "41"],
    price: 215,
    oldPrice: null,
    tag: "Original",
    tone: "#e0ddd5",
    image: "assets/zapatillas-nike-air.jpeg"
  },
  {
    id: 25,
    name: "Gorra Nike",
    category: "accesorios",
    categoryLabel: "Gorra · Nike",
    details: "Talla unica",
    sizes: [],
    price: 90,
    oldPrice: null,
    tag: "Original",
    tone: "#ded3bf",
    image: "assets/gorra-nike-nueva.jpeg"
  },
  {
    id: 26,
    name: "Sandalia Nike Victori One",
    category: "calzado",
    categoryLabel: "Sandalias · Nike",
    details: "Tallas 35.5 · 36.5 · 38 · 39",
    sizes: ["35.5", "36.5", "38", "39"],
    price: 115,
    oldPrice: null,
    tag: "Original",
    tone: "#d7d7d2",
    image: "assets/sandalia-nike-victori-one.jpeg"
  },
  {
    id: 27,
    name: "Nike Sabrina Ionescu",
    category: "ropa",
    categoryLabel: "Polo · Nike Sabrina Ionescu",
    details: "Talla M · L",
    sizes: ["M", "L"],
    price: 89,
    oldPrice: 159,
    tag: "Oferta",
    tagClass: "tag-sale",
    note: "Precio retail S/ 159",
    tone: "#151515",
    image: "assets/nike-sabrina-ionescu.jpeg"
  },
  {
    id: 28,
    name: "Polo Calvin Klein",
    category: "ropa",
    categoryLabel: "Polo · Calvin Klein",
    details: "Talla M",
    sizes: ["M"],
    price: 130,
    oldPrice: null,
    tag: "Original",
    tagClass: "",
    note: "Talla M",
    tone: "#eeeeee",
    image: "assets/polo-calvin-klein.jpeg"
  }
];
