const existingProducts = [
  {
    id: 1,
    name: "Sandalia Kappa",
    category: "calzado",
    categoryLabel: "Sandalias · Kappa",
    details: "Tallas 43 · 44 · 45",
    sizes: ["43", "44", "45"],
    price: 40,
    oldPrice: null,
    tag: "Solo por hoy",
    tagClass: "tag-sale",
    note: "Pago completo",
    tone: "#c7c9c8",
    image: "assets/sandalia-kappa.jpeg"
  },
  {
    id: 2,
    name: "Polo Jordan",
    category: "ropa",
    categoryLabel: "Polo · Jordan",
    details: "Talla M",
    sizes: ["M"],
    price: 130,
    oldPrice: null,
    tag: "Original",
    note: "Separa con S/ 40 · llega en 10 días",
    tone: "#b8d0e9",
    image: "assets/polo-jordan.jpeg"
  },
  {
    id: 3,
    name: "Gorra BMW",
    category: "accesorios",
    categoryLabel: "Gorra · BMW",
    details: "Talla única",
    sizes: [],
    price: 65,
    oldPrice: null,
    tag: "Original",
    tone: "#ded3bf",
    image: "assets/gorra-1.jpeg"
  },
  {
    id: 4,
    name: "Gorra Guess",
    category: "accesorios",
    categoryLabel: "Gorra · Guess",
    details: "",
    sizes: [],
    price: 135,
    oldPrice: null,
    referencePrice: 179.90,
    referenceType: "market-reference",
    referenceLabel: "Precio referencial",
    saleLabel: "Oferta Santos7",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    tone: "#aaa0ec",
    image: "assets/gorra-guess.jpeg"
  },
  {
    id: 5,
    name: "Polo Nike",
    category: "ropa",
    categoryLabel: "Polo · Nike",
    details: "Tallas M · L",
    sizes: ["M", "L"],
    price: 89,
    oldPrice: null,
    tag: "Original",
    tone: "#f0a08b",
    image: "assets/polo-nike.jpeg"
  },
  {
    id: 6,
    name: "Puma Suede XL",
    category: "calzado",
    categoryLabel: "Zapatillas · Puma",
    details: "Tallas 40.5 · 41 · 42 · 42.5 · 44.5",
    sizes: ["40.5", "41", "42", "42.5", "44.5"],
    price: 235,
    oldPrice: null,
    tag: "Original",
    tone: "#cee480",
    image: "assets/puma-suede-xl.jpeg"
  },
  {
    id: 7,
    name: "Puma Ferrari CA Match",
    category: "calzado",
    categoryLabel: "Zapatillas · Puma Ferrari",
    details: "Tallas 42 · 42.5 · 44.5",
    sizes: ["42", "42.5", "44.5"],
    price: 175,
    oldPrice: null,
    tag: "Original",
    tone: "#efb09c",
    image: "assets/puma-ferrari-ca-match.jpeg"
  },
  {
    id: 8,
    name: "Polo Puma",
    category: "ropa",
    categoryLabel: "Polo · Puma",
    details: "Tallas S · M · L · XL",
    sizes: ["S", "M", "L", "XL"],
    price: 59,
    oldPrice: null,
    tag: "Original",
    tone: "#a9caff",
    image: "assets/polo-puma-nuevo.jpeg"
  },
  {
    id: 9,
    name: "Camisero Puma BMW",
    category: "ropa",
    categoryLabel: "Camisero · Puma BMW",
    details: "Talla M",
    sizes: ["M"],
    price: 100,
    oldPrice: null,
    tag: "Solo quedan 2",
    tagClass: "tag-sale",
    note: "Stock limitado",
    tone: "#b8b9bd",
    image: "assets/camisero-puma-bmw.jpeg"
  },
  {
    id: 10,
    name: "Nike Air Max SC",
    category: "calzado",
    categoryLabel: "Zapatillas · Nike",
    details: "Tallas 40.5 · 41 · 42 · 42.5 · 43 · 44 · 44.5",
    sizes: ["40.5", "41", "42", "42.5", "43", "44", "44.5"],
    price: 239,
    oldPrice: null,
    tag: "Original",
    tone: "#f0a08b",
    image: "assets/nike-air-max-sc.jpeg"
  },
  {
    id: 11,
    name: "Sandalia Victori One",
    category: "calzado",
    categoryLabel: "Sandalias · Victori One",
    details: "Talla 39",
    sizes: ["39"],
    price: 85,
    oldPrice: null,
    tag: "Original",
    tone: "#d7d7d2",
    image: "assets/sandalias-1.jpeg"
  },
  {
    id: 12,
    name: "Nike Ebernon Low",
    category: "calzado",
    categoryLabel: "Zapatillas · Nike",
    details: "Tallas 41 · 42 · 42.5 · 43 · 44 · 44.5 · 45",
    sizes: ["41", "42", "42.5", "43", "44", "44.5", "45"],
    price: 189,
    oldPrice: null,
    tag: "Original",
    tone: "#ded3bf",
    image: "assets/nike-ebernon-low.jpeg"
  },
  {
    id: 13,
    name: "Polo Guess",
    category: "ropa",
    categoryLabel: "Polo · Guess",
    details: "Talla S",
    sizes: ["S"],
    price: 100,
    oldPrice: null,
    tag: "Original",
    tone: "#d0b5d8",
    image: "assets/polo-guess-nuevo.jpeg"
  },
  {
    id: 14,
    name: "Cartera Guess",
    category: "accesorios",
    categoryLabel: "Cartera · Guess",
    details: "Talla única",
    sizes: [],
    price: 259,
    oldPrice: null,
    tag: "Original",
    tone: "#d5c3a7",
    image: "assets/cartera-guess.jpeg"
  },
  {
    id: 15,
    name: "Sandalia Calvin Klein",
    category: "calzado",
    categoryLabel: "Sandalias · Calvin Klein",
    details: "Talla 40",
    sizes: ["40"],
    price: 115,
    oldPrice: null,
    tag: "Sin box",
    tagClass: "tag-sale",
    note: "Sin caja",
    tone: "#d6d2ca",
    image: "assets/sandalias-calvin-klein.jpeg"
  },
  {
    id: 16,
    name: "Polera Puma",
    category: "ropa",
    categoryLabel: "Polera · Puma",
    details: "Tallas S · M",
    sizes: ["S", "M"],
    price: 99,
    oldPrice: null,
    tag: "Original",
    tone: "#b8c6b5",
    image: "assets/polera-puma.jpeg"
  },
  {
    id: 17,
    name: "Polo Tommy Hilfiger",
    category: "ropa",
    categoryLabel: "Polo · Tommy Hilfiger",
    details: "Talla M",
    sizes: ["M"],
    price: 125,
    oldPrice: null,
    tag: "Original",
    tone: "#d9c7b2",
    image: "assets/polo-tommy-hilfiger-nuevo.jpeg"
  },
  {
    id: 18,
    name: "Sandalia Nike Kobe Offcourt",
    category: "calzado",
    categoryLabel: "Sandalias · Nike",
    details: "Talla 42.5",
    sizes: ["42.5"],
    price: 149,
    oldPrice: null,
    tag: "Original",
    tone: "#d5d8dc",
    image: "assets/sandalias-nike.jpeg"
  },
  {
    id: 19,
    name: "Sandalia Puma",
    category: "calzado",
    categoryLabel: "Sandalias · Puma",
    details: "Talla 40.5",
    sizes: ["40.5"],
    price: 69,
    oldPrice: null,
    tag: "Preciazoo",
    tagClass: "tag-sale",
    tone: "#c5c2ba",
    image: "assets/sandalia-puma.jpeg"
  },
  {
    id: 20,
    name: "Polo",
    category: "ropa",
    categoryLabel: "Polo",
    details: "Talla S",
    sizes: ["S"],
    price: 69,
    oldPrice: null,
    tag: "Original",
    tone: "#c9c9c9",
    image: "assets/polo-4.jpeg"
  },
  {
    id: 21,
    name: "Polo Nike",
    category: "ropa",
    categoryLabel: "Polo · Nike",
    details: "Tallas S · M · XL",
    sizes: ["S", "M", "XL"],
    price: 90,
    oldPrice: null,
    tag: "Original",
    tone: "#bfc3c4",
    image: "assets/polo-nike-negro.jpeg"
  },
  {
    id: 22,
    name: "Sandalia",
    category: "calzado",
    categoryLabel: "Sandalias",
    details: "Talla 40",
    sizes: ["40"],
    price: 85,
    oldPrice: null,
    tag: "Original",
    tone: "#b9c0c6",
    image: "assets/sandalias-2.jpeg"
  },
  {
    id: 23,
    name: "Zapatillas Nike",
    category: "calzado",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla 40",
    sizes: ["40"],
    price: 415,
    oldPrice: null,
    tag: "Caja cortada",
    tagClass: "tag-sale",
    note: "Caja cortada",
    tone: "#d7dbe0",
    image: "assets/zapatillas-nike.jpeg"
  },
  {
    id: 24,
    name: "Zapatillas Nike Air",
    category: "calzado",
    categoryLabel: "Zapatillas · Nike",
    details: "Tallas 39 · 40 · 41",
    sizes: ["39", "40", "41"],
    price: 215,
    oldPrice: null,
    tag: "Original",
    tone: "#e0ddd5",
    image: "assets/zapatillas-nike-air.jpeg"
  },
  {
    id: 25,
    name: "Gorra Nike",
    category: "accesorios",
    categoryLabel: "Gorra · Nike",
    details: "Talla única",
    sizes: [],
    price: 90,
    oldPrice: null,
    tag: "Original",
    tone: "#ded3bf",
    image: "assets/gorra-nike-nueva.jpeg"
  },
  {
    id: 26,
    name: "Sandalia Nike Victori One",
    category: "calzado",
    categoryLabel: "Sandalias · Nike",
    details: "Tallas 35.5 · 36.5 · 38 · 39",
    sizes: ["35.5", "36.5", "38", "39"],
    price: 115,
    oldPrice: null,
    tag: "Original",
    tone: "#d7d7d2",
    image: "assets/sandalia-nike-victori-one.jpeg"
  },
  {
    id: 27,
    name: "Nike Sabrina Ionescu",
    category: "ropa",
    categoryLabel: "Polo · Nike Sabrina Ionescu",
    details: "Tallas M · L",
    sizes: ["M", "L"],
    price: 89,
    oldPrice: 159,
    referencePrice: 159,
    referenceType: "retail",
    referenceLabel: "Precio retail",
    saleLabel: "Oferta Santos7",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio retail S/ 159",
    tone: "#151515",
    image: "nike sabrina.jpeg"
  },
  {
    id: 28,
    name: "Polo Calvin Klein",
    category: "ropa",
    categoryLabel: "Polo · Calvin Klein",
    details: "Talla M",
    sizes: ["M"],
    price: 130,
    oldPrice: null,
    tag: "Original",
    tone: "#eeeeee",
    image: "polo calvin klein.jpeg"
  }
];

const newSneakers = [
  {
    id: 29,
    name: "Cosmic Runner (GS)",
    brand: "Nike",
    model: "Cosmic Runner (GS)",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla BR 34",
    sizeSystem: "BR",
    sizes: ["34"],
    stock: 1,
    stockBySize: { "34": 1 },
    price: 219.90,
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/197863485607_1_20250326-mrtPeru.jpg"],
    image: "img1/197863485607_1_20250326-mrtPeru.jpg",
    imageFit: "contain",
    tag: "Nuevo ingreso",
    note: "1 unidad",
    tone: "#e9edf0"
  },
  {
    id: 30,
    name: "Phantom GX Club TF",
    brand: "Nike",
    model: "Phantom GX Club TF",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Tallas BR 39.5 · 41",
    sizeSystem: "BR",
    sizes: ["39.5", "41"],
    stock: 2,
    stockBySize: { "39.5": 1, "41": 1 },
    price: 289.90,
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/nike phantom.webp"],
    image: "img1/nike phantom.webp",
    imageFit: "contain",
    tag: "Nuevo ingreso",
    note: "2 unidades",
    tone: "#e8edf1"
  },
  {
    id: 31,
    name: "Run Swift 2 (W)",
    brand: "Nike",
    model: "Run Swift 2 (W)",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Tallas BR 35 · 33",
    sizeSystem: "BR",
    sizes: ["35", "33"],
    stock: 2,
    stockBySize: { "35": 1, "33": 1 },
    price: 339.90,
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/nike srum.jpg"],
    image: "img1/nike srum.jpg",
    imageFit: "contain",
    tag: "Nuevo ingreso",
    note: "2 unidades",
    tone: "#e8e8e8"
  },
  {
    id: 32,
    name: "In-Season TR 13 (W)",
    brand: "Nike",
    model: "In-Season TR 13 (W)",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Tallas BR 34 · 32.5",
    sizeSystem: "BR",
    sizes: ["34", "32.5"],
    stock: 2,
    stockBySize: { "34": 1, "32.5": 1 },
    price: 349.90,
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/nike sa.jpg"],
    image: "img1/nike sa.jpg",
    imageFit: "contain",
    tag: "Nuevo ingreso",
    note: "2 unidades",
    tone: "#e9edf0"
  },
  {
    id: 33,
    name: "Legend 10 Club TF",
    brand: "Nike",
    model: "Legend 10 Club TF",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Tallas BR 41 · 43",
    sizeSystem: "BR",
    sizes: ["41", "43"],
    stock: 2,
    stockBySize: { "41": 1, "43": 1 },
    price: 199.90,
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/tiempo legent.jpg"],
    image: "img1/tiempo legent.jpg",
    imageFit: "contain",
    tag: "Nuevo ingreso",
    note: "2 unidades · revisar color en consulta",
    tone: "#efedf0"
  },
  {
    id: 34,
    name: "Dunk Low Retro",
    brand: "Nike",
    model: "Dunk Low Retro",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Tallas BR 41 · 41.5 · 42",
    sizeSystem: "BR",
    sizes: ["41", "41.5", "42"],
    stock: 3,
    stockBySize: { "41": 1, "41.5": 1, "42": 1 },
    price: 459.90,
    priceKind: "official-approx",
    availability: "in_stock",
    images: ["img1/dump.jpg"],
    image: "img1/dump.jpg",
    imageFit: "contain",
    tag: "Nuevo ingreso",
    note: "Precio oficial aprox. · 3 unidades",
    tone: "#e9edf0"
  },
  {
    id: 35,
    name: "W Nike AL8",
    brand: "Nike",
    model: "W Nike AL8",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla BR 34.5",
    sizeSystem: "BR",
    sizes: ["34.5"],
    stock: 1,
    stockBySize: { "34.5": 1 },
    price: 399.90,
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/air max.webp"],
    image: "img1/air max.webp",
    imageFit: "contain",
    tag: "Nuevo ingreso",
    note: "1 unidad",
    tone: "#e9edf0"
  },
  {
    id: 36,
    name: "Nike Air Max Nuaxis",
    brand: "Nike",
    model: "Air Max Nuaxis",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla BR 39",
    sizeSystem: "BR",
    sizes: ["39"],
    stock: 1,
    stockBySize: { "39": 1 },
    price: 329.90,
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/nike air max.webp"],
    image: "img1/nike air max.webp",
    imageFit: "contain",
    tag: "Nuevo ingreso",
    note: "1 unidad",
    tone: "#e9edf0"
  },
  {
    id: 37,
    name: "Victori One Shower Slide (W)",
    brand: "Nike",
    model: "Victori One Shower Slide (W)",
    category: "calzado",
    subCategory: "sandalias",
    categoryLabel: "Sandalias · Nike",
    details: "Talla BR 37.5",
    sizeSystem: "BR",
    sizes: ["37.5"],
    stock: 1,
    stockBySize: { "37.5": 1 },
    price: 149.90,
    priceKind: "official-approx",
    availability: "in_stock",
    images: ["img1/image (1).png"],
    image: "img1/image (1).png",
    imageFit: "contain",
    tag: "Nuevo ingreso",
    note: "Precio oficial aprox. · 1 unidad",
    tone: "#f1f1f1"
  },
  {
    id: 38,
    name: "Victori One Slide",
    brand: "Nike",
    model: "Victori One Slide",
    category: "calzado",
    subCategory: "sandalias",
    categoryLabel: "Sandalias · Nike",
    details: "Talla BR 39",
    sizeSystem: "BR",
    sizes: ["39"],
    stock: 1,
    stockBySize: { "39": 1 },
    price: 149.90,
    priceKind: "official-approx",
    availability: "in_stock",
    images: ["img1/image (6).png"],
    image: "img1/image (6).png",
    imageFit: "contain",
    tag: "Nuevo ingreso",
    note: "Precio oficial aprox. · 1 unidad",
    tone: "#e7ebef"
  },
  {
    id: 39,
    name: "Pacific LTR (W)",
    brand: "Nike",
    model: "Pacific LTR (W)",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla BR 37.5",
    sizeSystem: "BR",
    sizes: ["37.5"],
    stock: 2,
    stockBySize: { "37.5": 2 },
    price: 139,
    referencePrice: 279.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    referenceSource: "https://www.nike.com.pe/nike-pacific-ltr-zapatillas-para-ninos-grandes/iq4052-001/11100049006.html",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/image (3).png"],
    image: "img1/image (3).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "2 unidades · precio Nike de referencia",
    tone: "#e9edf0"
  },
  {
    id: 40,
    name: "Air Jordan 1 Mid SE",
    brand: "Jordan",
    model: "Air Jordan 1 Mid SE",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Jordan",
    details: "Talla BR 41",
    sizeSystem: "BR",
    sizes: ["41"],
    stock: 1,
    stockBySize: { "41": 1 },
    price: 599.90,
    priceKind: "official-approx",
    availability: "in_stock",
    images: ["img1/Air Jordan 1 Mid.png"],
    image: "img1/Air Jordan 1 Mid.png",
    imageFit: "contain",
    tag: "Nuevo ingreso",
    note: "Precio oficial aprox. · 1 unidad",
    tone: "#e8ebee"
  },
  {
    id: 41,
    name: "Air Force 1 '07",
    brand: "Nike",
    model: "Air Force 1 '07",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla BR 40",
    sizeSystem: "BR",
    sizes: ["40"],
    stock: 1,
    stockBySize: { "40": 1 },
    price: 385,
    referencePrice: 549.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    referenceSource: "https://www.nike.com.pe/productos/calzado/af1",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/image (2).png", "img1/image (11).png"],
    image: "img1/image (2).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio Nike de referencia · 1 unidad",
    tone: "#efeee9"
  },
  {
    id: 42,
    name: "Adidas · caja negra",
    brand: "Adidas",
    model: null,
    category: "calzado",
    subCategory: "otros",
    categoryLabel: "Calzado · Adidas",
    details: "Modelo no visible",
    sizeSystem: "",
    sizes: [],
    stock: 1,
    stockBySize: null,
    price: null,
    priceKind: "pending",
    availability: "inquiry",
    images: [],
    image: null,
    imageFit: "contain",
    tag: "Consultar",
    note: "Modelo no visible · caja negra · 1 unidad",
    tone: "#e9e9e9"
  },
  {
    id: 43,
    name: "Palermo Moda Tongue Wns",
    brand: "Puma",
    model: "Palermo Moda Tongue Wns",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Puma",
    details: "Talla BR 34.5",
    sizeSystem: "BR",
    sizes: ["34.5"],
    stock: 1,
    stockBySize: { "34.5": 1 },
    price: 159,
    referencePrice: 429.90,
    referenceType: "retail",
    referenceLabel: "Precio retail",
    referenceSource: "https://thn.pe/products/zapatillas-urbano-mujer-puma-palermo-moda-tongue-wns-401679-03",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/puma polermo.jpg"],
    image: "img1/puma polermo.jpg",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio retail de referencia · 1 unidad",
    tone: "#e9e4d9"
  },
  {
    id: 44,
    name: "Puma-180",
    brand: "Puma",
    model: "Puma-180",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Puma",
    details: "Talla BR 35",
    sizeSystem: "BR",
    sizes: ["35"],
    stock: 1,
    stockBySize: { "35": 1 },
    price: 349.90,
    priceKind: "official-approx",
    availability: "in_stock",
    images: ["img1/urbano-puma.jpg"],
    image: "img1/urbano-puma.jpg",
    imageFit: "contain",
    tag: "Nuevo ingreso",
    note: "Precio oficial aprox. · 1 unidad",
    tone: "#ededed"
  },
  {
    id: 45,
    name: "RS-X Paisley Wns",
    brand: "Puma",
    model: "RS-X Paisley Wns",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Puma",
    details: "Talla BR 37",
    sizeSystem: "BR",
    sizes: ["37"],
    stock: 1,
    stockBySize: { "37": 1 },
    price: 499.90,
    priceKind: "official-approx",
    availability: "in_stock",
    images: ["img1/zapatilla rs.png"],
    image: "img1/zapatilla rs.png",
    imageFit: "contain",
    tag: "Nuevo ingreso",
    note: "Precio oficial aprox. · 1 unidad",
    tone: "#eee8e4"
  },
  {
    id: 46,
    name: "Suede XL Lth",
    brand: "Puma",
    model: "Suede XL Lth",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Puma",
    details: "Talla BR 39",
    sizeSystem: "BR",
    sizes: ["39"],
    stock: 1,
    stockBySize: { "39": 1 },
    price: 399.90,
    priceKind: "official-approx",
    availability: "in_stock",
    images: ["img1/PUMA XL.jpeg"],
    image: "img1/PUMA XL.jpeg",
    imageFit: "contain",
    tag: "Nuevo ingreso",
    note: "Precio oficial aprox. · 1 unidad",
    tone: "#eee9e7"
  },
  {
    id: 47,
    name: "Puma x Model Teague Wns",
    brand: "Puma",
    model: "Puma x Model Teague Wns",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Puma",
    details: "Talla por confirmar",
    sizeSystem: "",
    sizes: [],
    stock: 1,
    stockBySize: null,
    price: 399.90,
    priceKind: "official-approx",
    availability: "in_stock",
    images: ["img1/Zapatillas Suede XL unisex.png"],
    image: "img1/Zapatillas Suede XL unisex.png",
    imageFit: "contain",
    tag: "Nuevo ingreso",
    note: "Precio oficial aprox. · foto de referencia · talla por confirmar",
    tone: "#e9e9e9"
  },
  {
    id: 65,
    name: "Nike Jr. Mercurial Vapor 16 Academy",
    brand: "Nike",
    model: "Jr. Mercurial Vapor 16 Academy",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla por confirmar",
    sizeSystem: "BR",
    sizes: [],
    stock: 1,
    stockBySize: null,
    price: 299.90,
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/chimpunes.jpg"],
    image: "img1/chimpunes.jpg",
    imageFit: "contain",
    tag: "Nuevo ingreso",
    note: "1 unidad · talla por confirmar",
    tone: "#e9edf0"
  },
  {
    id: 66,
    name: "Nike Tiempo Legend 9 Academy TF",
    brand: "Nike",
    model: "Tiempo Legend 9 Academy TF",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla por confirmar",
    sizeSystem: "BR",
    sizes: [],
    stock: 1,
    stockBySize: null,
    price: 369.90,
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/tiempo leguent.webp"],
    image: "img1/tiempo leguent.webp",
    imageFit: "contain",
    tag: "Nuevo ingreso",
    note: "1 unidad · talla por confirmar",
    tone: "#e9edf0"
  }
];

const consultableProducts = [
  {
    id: 48,
    name: "Adidas Adilette azul",
    brand: "Adidas",
    model: "Adilette",
    category: "calzado",
    subCategory: "sandalias",
    categoryLabel: "Sandalias · Adidas",
    details: "Talla por confirmar",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 95,
    referencePrice: 129,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    referenceSource: "https://www.adidas.pe/sandalias-adilette/288022.html",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (5).png"],
    image: "img1/image (5).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio adidas de referencia · talla por confirmar",
    tone: "#e8ecef"
  },
  {
    id: 49,
    name: "Nike Victori One Shower Slide",
    brand: "Nike",
    model: "Victori One Shower Slide",
    category: "calzado",
    subCategory: "sandalias",
    categoryLabel: "Sandalias · Nike",
    details: "Talla por confirmar",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 85,
    referencePrice: 119.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    referenceSource: "https://www.nike.com.pe/nike-victori-one-sandalias-de-ducha-para-mujer/cz7836-001/10696713011.html",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (7).png"],
    image: "img1/image (7).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio Nike de referencia · talla por confirmar",
    tone: "#e9e9e9"
  },
  {
    id: 50,
    name: "Fila Drifter Basic",
    brand: "Fila",
    model: "Drifter Basic",
    category: "calzado",
    subCategory: "sandalias",
    categoryLabel: "Sandalias · Fila",
    details: "Talla por confirmar",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 60,
    referencePrice: 119.90,
    referenceType: "retail",
    referenceLabel: "Precio retail",
    referenceSource: "https://platanitos.com/pe/producto/fila-sandalia-hombre-ojota-drifter-basic-blanco-fdw620r8edqd",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (10).png"],
    image: "img1/image (10).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio retail de referencia · talla por confirmar",
    tone: "#f0f0f0"
  },
  {
    id: 51,
    name: "Nike Air Max Dn",
    brand: "Nike",
    model: "Air Max Dn",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla por confirmar",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 400,
    referencePrice: 759.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    referenceSource: "https://www.nike.com.pe/nike-air-max-dn-zapatillas-para-hombre/dv3337-016/11019364016.html",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (9).png"],
    image: "img1/image (9).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio Nike de referencia · talla por confirmar",
    tone: "#edf0f1"
  },
  {
    id: 52,
    name: "Puma Leadcat 2.0",
    brand: "Puma",
    model: "Leadcat 2.0",
    category: "calzado",
    subCategory: "sandalias",
    categoryLabel: "Sandalias · Puma",
    details: "Talla por confirmar",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 85,
    referencePrice: 119.90,
    referenceType: "market-reference",
    referenceLabel: "Precio referencial",
    referenceSource: "https://pe.puma.com/pd/sandalias-leadcat-2.0/384139.html",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (8).png"],
    image: "img1/image (8).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio PUMA de referencia · talla por confirmar",
    tone: "#e9e9e9"
  },
  {
    id: 53,
    name: "Fila Drifter Basic negro/rojo",
    brand: "Fila",
    model: "Drifter Basic negro/rojo",
    category: "calzado",
    subCategory: "sandalias",
    categoryLabel: "Sandalias · Fila",
    details: "Talla por confirmar",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 60,
    referencePrice: 119.90,
    referenceType: "retail",
    referenceLabel: "Precio retail",
    referenceSource: "https://platanitos.com/pe/producto/fila-sandalia-hombre-ojota-drifter-basic-blanco-fdw620r8edqd",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (21).png"],
    image: "img1/image (21).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio retail de referencia · talla por confirmar",
    tone: "#e9e9e9"
  },
  {
    id: 54,
    name: "Nike Victori One Slide",
    brand: "Nike",
    model: "Victori One Slide",
    category: "calzado",
    subCategory: "sandalias",
    categoryLabel: "Sandalias · Nike",
    details: "Talla por confirmar",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 100,
    referencePrice: 139.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    referenceSource: "https://www.nike.com.pe/nike-victori-one-sandalia-para-mujer/cn9677-011/11099076011.html",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/sandalia Nike tipo slide.png"],
    image: "img1/sandalia Nike tipo slide.png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio Nike de referencia · talla por confirmar",
    tone: "#e4e8ee"
  },
  {
    id: 55,
    name: "Pack x3 polos New Balance",
    brand: "New Balance",
    model: "Pack x3 polos",
    category: "ropa",
    subCategory: "polos",
    categoryLabel: "Polos · New Balance",
    details: "Talla por confirmar · pack de 3",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 99,
    referencePrice: 149,
    referenceType: "market-reference",
    referenceLabel: "Precio referencial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (12).png"],
    image: "img1/image (12).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Pack de 3 · talla por confirmar",
    tone: "#f0f0f0"
  },
  {
    id: 56,
    name: "Jordan Flight Modal · pack x2",
    brand: "Jordan",
    model: "Flight Modal · pack x2",
    category: "ropa",
    subCategory: "polos",
    categoryLabel: "Polos · Jordan",
    details: "Talla M · pack de 2",
    sizes: ["M"],
    stock: null,
    stockBySize: null,
    price: 149.90,
    referencePrice: 199.90,
    referenceType: "market-reference",
    referenceLabel: "Precio referencial",
    referenceSource: "https://www.nike.com/t/jordan-mens-modal-undershirt-2-pack-XymUidhO",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (13).png"],
    image: "img1/image (13).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Pack de 2 · talla M · precio referencial",
    tone: "#e5e5e5"
  },
  {
    id: 57,
    name: "Gorra Nike gris",
    brand: "Nike",
    model: "Gorra gris",
    category: "accesorios",
    subCategory: "gorras",
    categoryLabel: "Gorras · Nike",
    details: "Talla única",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 85,
    referencePrice: 99.90,
    referenceType: "market-reference",
    referenceLabel: "Precio referencial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (14).png"],
    image: "img1/image (14).png",
    imageFit: "cover",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio Nike de referencia · talla única",
    tone: "#e8e8e8"
  },
  {
    id: 58,
    name: "Gorra BMW Motorsport",
    brand: "BMW",
    model: "Motorsport",
    category: "accesorios",
    subCategory: "gorras",
    categoryLabel: "Gorras · BMW",
    details: "Talla única",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 100,
    referencePrice: 129.90,
    referenceType: "market-reference",
    referenceLabel: "Precio referencial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (15).png"],
    image: "img1/image (15).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Talla única · precio referencial de mercado",
    tone: "#f0f0f0"
  },
  {
    id: 59,
    name: "Gorra Guess monogram",
    brand: "Guess",
    model: "Monogram",
    category: "accesorios",
    subCategory: "gorras",
    categoryLabel: "Gorras · Guess",
    details: "Talla única",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 100,
    referencePrice: 135,
    referenceType: "market-reference",
    referenceLabel: "Precio referencial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (16).png"],
    image: "img1/image (16).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Talla única · precio referencial de mercado",
    tone: "#e7e3de"
  },
  {
    id: 60,
    name: "Gorra Guess negra",
    brand: "Guess",
    model: "Gorra negra",
    category: "accesorios",
    subCategory: "gorras",
    categoryLabel: "Gorras · Guess",
    details: "Talla única",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 135,
    referencePrice: 179.90,
    referenceType: "market-reference",
    referenceLabel: "Precio referencial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (17).png"],
    image: "img1/image (17).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Talla única · precio referencial de mercado",
    tone: "#e9e9e9"
  },
  {
    id: 61,
    name: "Gorra Nike blanca",
    brand: "Nike",
    model: "Gorra blanca",
    category: "accesorios",
    subCategory: "gorras",
    categoryLabel: "Gorras · Nike",
    details: "Talla única",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 90,
    referencePrice: 99.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    referenceSource: "https://www.nike.com.pe/gorra-sportswear-heritage-86/943092-010/10244929001.html",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (18).png"],
    image: "img1/image (18).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio Nike de referencia · talla única",
    tone: "#f0f0f0"
  },
  {
    id: 62,
    name: "Gorra Tommy Hilfiger beige",
    brand: "Tommy Hilfiger",
    model: "Gorra beige",
    category: "accesorios",
    subCategory: "gorras",
    categoryLabel: "Gorras · Tommy Hilfiger",
    details: "Talla única",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 135,
    referencePrice: 169.90,
    referenceType: "market-reference",
    referenceLabel: "Precio referencial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (19).png"],
    image: "img1/image (19).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Talla única · precio referencial de mercado",
    tone: "#eee5d9"
  },
  {
    id: 63,
    name: "Polo Puma F1",
    brand: "Puma",
    model: "F1 Essentials Logo",
    category: "ropa",
    subCategory: "polos",
    categoryLabel: "Polos · Puma F1",
    details: "Talla por confirmar",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 70,
    referencePrice: 99,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    referenceSource: "https://pe.puma.com/pd/polo-f1-essentials-logo-para-hombre/633264.html",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (22).png"],
    image: "img1/image (22).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio PUMA de referencia · talla por confirmar",
    tone: "#f0f0f0"
  },
  {
    id: 64,
    name: "Mochila Kobe / FCB",
    brand: "Nike",
    model: "Kobe / FCB",
    category: "accesorios",
    subCategory: "mochilas",
    categoryLabel: "Mochilas · Nike",
    details: "Medidas por confirmar",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 100,
    referencePrice: 179.90,
    referenceType: "market-reference",
    referenceLabel: "Precio referencial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (23).png"],
    image: "img1/image (23).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Medidas por confirmar · precio referencial de mercado",
    tone: "#e9e9e9"
  },
  {
    id: 67,
    name: "Gorra Puma · referencia",
    brand: "Puma",
    model: "Gorra clásica",
    category: "accesorios",
    subCategory: "gorras",
    categoryLabel: "Gorras · Puma",
    details: "Talla única · foto por confirmar",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 69,
    referencePrice: 99,
    referenceType: "market-reference",
    referenceLabel: "Precio referencial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: [],
    image: null,
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Talla y foto por confirmar · precio referencial de mercado",
    tone: "#eeeeee"
  }
];

export const products = [...existingProducts, ...newSneakers, ...consultableProducts];
