const existingProducts = [
  {
    id: 1,
    name: "Sandalias Kappa",
    category: "calzado",
    categoryLabel: "Sandalias · Kappa",
    details: "Tallas EUR 43 · 44 · 45",
    sizeSystem: "EUR",
    sizes: ["43", "44", "45"],
    price: 40,
    oldPrice: null,
    tag: "Pago completo",
    note: "Sin descuento · pago completo",
    tone: "#c7c9c8",
    image: "assets/sandalia-kappa.jpeg"
  },
  {
    id: 2,
    name: "Jordan T-shirt",
    category: "ropa",
    categoryLabel: "T-shirt · Jordan",
    details: "Talla M · entrega en 7 días",
    sizes: ["M"],
    price: 130,
    priceLabel: "S/ 40 para separar",
    depositPrice: 40,
    oldPrice: null,
    tag: "Reserva",
    note: "Pago parcial · separa con S/ 40 · total S/ 130 · llega en 7 días",
    tone: "#b8d0e9",
    image: null,
    images: []
  },
  {
    id: 3,
    name: "BMW Cap",
    category: "accesorios",
    categoryLabel: "Gorras · BMW",
    details: "Talla única",
    sizes: [],
    price: 65,
    oldPrice: null,
    tag: "Original",
    tone: "#ded3bf",
    image: "assets/gorra-1.jpeg"
  },
  {
    id: 4,
    name: "Gucci-style Cap",
    brand: "Gucci",
    model: "Gucci-style Cap",
    category: "accesorios",
    categoryLabel: "Gorras · Gucci",
    details: "",
    sizes: [],
    price: 135,
    oldPrice: null,
    referencePrice: 179.90,
    referenceType: "market-reference",
    referenceLabel: "Precio referencial",
    saleLabel: "Oferta Santos7",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Oferta Santos7 · talla única",
    tone: "#aaa0ec",
    image: "assets/gorra-guess.jpeg"
  },
  {
    id: 5,
    name: "Polo Nike Algodón",
    brand: "Nike",
    model: "Nike Sportswear Club Cotton Tee",
    styleCode: "AR4997-538",
    category: "ropa",
    subCategory: "polos",
    categoryLabel: "Polos · Nike",
    details: "Tallas M · L",
    sizes: ["M", "L"],
    price: 80,
    referencePrice: 79.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    priceKind: "store",
    availability: "in_stock",
    tag: "Original",
    note: "Polo Nike Algodón · tallas M y L",
    tone: "#eeeeec",
    images: ["POLO.jpeg"],
    image: "POLO.jpeg",
    imageFit: "cover"
  },
  {
    id: 6,
    name: "Puma Suede XL",
    category: "calzado",
    categoryLabel: "Zapatillas · Puma",
    details: "Tallas EUR 40.5 y 41",
    sizeSystem: "EUR",
    sizes: ["40.5", "41"],
    price: 235,
    oldPrice: null,
    tag: "Original",
    tone: "#cee480",
    image: "assets/puma-suede-xl.jpeg"
  },
  {
    id: 7,
    name: "Puma Ferrari CA Match",
    category: "calzado",
    categoryLabel: "Zapatillas · Puma Ferrari",
    details: "Tallas EUR 42 · 42.5 · 44.5",
    sizeSystem: "EUR",
    sizes: ["42", "42.5", "44.5"],
    price: 175,
    stock: 0,
    availability: "out_of_stock",
    oldPrice: null,
    tag: "Original",
    tone: "#efb09c",
    image: "assets/puma-ferrari-ca-match.jpeg"
  },
  {
    id: 8,
    name: "Polo Puma",
    category: "ropa",
    categoryLabel: "Polo · Puma",
    details: "Tallas S · M · L · XL",
    sizes: ["S", "M", "L", "XL"],
    price: 59,
    oldPrice: null,
    tag: "Original",
    note: "Sin descuento",
    tone: "#a9caff",
    image: "assets/polo-puma-nuevo.jpeg"
  },
  {
    id: 9,
    name: "Camisero Puma BMW",
    category: "ropa",
    categoryLabel: "Camisero · Puma BMW",
    details: "Talla M",
    sizes: ["M"],
    price: 100,
    stock: 0,
    availability: "out_of_stock",
    oldPrice: null,
    tag: "Solo quedan 2",
    tagClass: "tag-sale",
    note: null,
    tone: "#b8b9bd",
    image: "assets/camisero-puma-bmw.jpeg"
  },
  {
    id: 10,
    name: "Nike Air Max SC",
    category: "calzado",
    categoryLabel: "Zapatillas · Nike",
    details: "Tallas EUR 40.5 · 41 · 42 · 42.5 · 43 · 44 · 44.5",
    sizeSystem: "EUR",
    sizes: ["40.5", "41", "42", "42.5", "43", "44", "44.5"],
    price: 239,
    stock: 0,
    availability: "out_of_stock",
    oldPrice: null,
    tag: "Original",
    tone: "#f0a08b",
    image: "assets/nike-air-max-sc.jpeg"
  },
  {
    id: 11,
    name: "Sandalia Victori One",
    category: "calzado",
    categoryLabel: "Sandalias · Victori One",
    details: "Talla EUR 39",
    sizeSystem: "EUR",
    sizes: ["39"],
    price: 85,
    oldPrice: null,
    tag: "Original",
    tone: "#d7d7d2",
    image: "assets/sandalias-1.jpeg"
  },
  {
    id: 12,
    name: "Nike Ebernon Low",
    category: "calzado",
    categoryLabel: "Zapatillas · Nike",
    details: "Tallas EUR 41 · 42 · 42.5 · 43 · 44 · 44.5 · 45",
    sizeSystem: "EUR",
    sizes: ["41", "42", "42.5", "43", "44", "44.5", "45"],
    price: 189,
    stock: 0,
    availability: "out_of_stock",
    oldPrice: null,
    tag: "Original",
    tone: "#ded3bf",
    image: "assets/nike-ebernon-low.jpeg"
  },
  {
    id: 13,
    name: "Polo Guess",
    category: "ropa",
    categoryLabel: "Polo · Guess",
    details: "Talla S",
    sizes: ["S"],
    price: 100,
    oldPrice: null,
    tag: "Original",
    tone: "#d0b5d8",
    image: "assets/polo-guess-nuevo.jpeg"
  },
  {
    id: 14,
    name: "Cartera Guess",
    category: "accesorios",
    categoryLabel: "Cartera · Guess",
    details: "Talla única",
    sizes: [],
    price: 259,
    oldPrice: null,
    tag: "Original",
    tone: "#d5c3a7",
    image: "assets/cartera-guess.jpeg"
  },
  {
    id: 15,
    name: "Sandalia Calvin Klein",
    category: "calzado",
    categoryLabel: "Sandalias · Calvin Klein",
    details: "Talla EUR 40",
    sizeSystem: "EUR",
    sizes: ["40"],
    price: 115,
    oldPrice: null,
    tag: "Sin box",
    tagClass: "tag-sale",
    note: "Sin caja",
    tone: "#d6d2ca",
    image: "assets/sandalias-calvin-klein.jpeg"
  },
  {
    id: 16,
    name: "Polera Puma",
    category: "ropa",
    categoryLabel: "Polera · Puma",
    details: "Talla M",
    sizes: ["M"],
    price: 99,
    oldPrice: null,
    tag: "Original",
    tone: "#b8c6b5",
    image: "assets/polera-puma.jpeg"
  },
  {
    id: 17,
    name: "Polo Tommy Hilfiger",
    category: "ropa",
    categoryLabel: "Polo · Tommy Hilfiger",
    details: "Talla M",
    sizes: ["M"],
    price: 125,
    oldPrice: null,
    tag: "Original",
    tone: "#d9c7b2",
    image: "assets/polo-tommy-hilfiger-nuevo.jpeg"
  },
  {
    id: 18,
    name: "Sandalia Nike Kobe Offcourt",
    category: "calzado",
    categoryLabel: "Sandalias · Nike",
    details: "Talla EUR 42.5",
    sizeSystem: "EUR",
    sizes: ["42.5"],
    price: 149,
    oldPrice: null,
    tag: "Original",
    tone: "#d5d8dc",
    image: "assets/sandalias-nike.jpeg"
  },
  {
    id: 19,
    name: "Sandalia Puma",
    category: "calzado",
    categoryLabel: "Sandalias · Puma",
    details: "Talla EUR 40.5",
    sizeSystem: "EUR",
    sizes: ["40.5"],
    price: 69,
    oldPrice: null,
    tag: "Preciazoo",
    tagClass: "tag-sale",
    tone: "#c5c2ba",
    image: "assets/sandalia-puma.jpeg"
  },
  {
    id: 20,
    name: "Polo",
    category: "ropa",
    categoryLabel: "Polo",
    details: "Tallas M y XL",
    sizes: ["M", "XL"],
    price: 89,
    oldPrice: null,
    tag: "Original",
    tone: "#c9c9c9",
    image: "assets/polo-4.jpeg"
  },
  {
    id: 21,
    name: "Polo Nike Negro",
    category: "ropa",
    categoryLabel: "Polo · Nike",
    details: "Tallas S y M",
    sizes: ["S", "M"],
    price: 90,
    oldPrice: null,
    tag: "Original",
    tone: "#bfc3c4",
    image: "assets/polo-nike-negro.jpeg"
  },
  {
    id: 22,
    name: "Sandalia",
    category: "calzado",
    categoryLabel: "Sandalias",
    details: "Talla EUR 40",
    sizeSystem: "EUR",
    sizes: ["40"],
    price: 85,
    oldPrice: null,
    tag: "Original",
    tone: "#b9c0c6",
    image: "assets/sandalias-2.jpeg"
  },
  {
    id: 23,
    name: "Zapatillas Nike",
    category: "calzado",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla EUR 40",
    sizeSystem: "EUR",
    sizes: ["40"],
    price: 415,
    oldPrice: null,
    tag: "Caja cortada",
    tagClass: "tag-sale",
    note: "Caja cortada",
    tone: "#d7dbe0",
    image: "assets/zapatillas-nike.jpeg"
  },
  {
    id: 24,
    name: "Zapatillas Nike Air",
    category: "calzado",
    categoryLabel: "Zapatillas · Nike",
    details: "Tallas EUR 40.5 y 41",
    sizeSystem: "EUR",
    sizes: ["40.5", "41"],
    price: 215,
    oldPrice: null,
    tag: "Original",
    tone: "#e0ddd5",
    image: "assets/zapatillas-nike-air.jpeg"
  },
  {
    id: 25,
    name: "Gorra Nike",
    category: "accesorios",
    categoryLabel: "Gorra · Nike",
    details: "Talla M/L",
    sizes: ["M/L"],
    price: 90,
    oldPrice: null,
    tag: "Original",
    tone: "#ded3bf",
    image: "assets/gorra-nike-nueva.jpeg"
  },
  {
    id: 26,
    name: "Sandalia Nike Victori One",
    category: "calzado",
    categoryLabel: "Sandalias · Nike",
    details: "Tallas EUR 40 y 41",
    sizeSystem: "EUR",
    sizes: ["40", "41"],
    price: 100,
    oldPrice: null,
    tag: "Original",
    tone: "#d7d7d2",
    image: "assets/sandalia-nike-victori-one.jpeg"
  },
  {
    id: 27,
    name: "Nike Sabrina Ionescu",
    category: "ropa",
    categoryLabel: "Polo · Nike Sabrina Ionescu",
    details: "Tallas M · L",
    sizes: ["M", "L"],
    price: 89,
    oldPrice: 159,
    referencePrice: 159,
    referenceType: "retail",
    referenceLabel: "Precio retail",
    saleLabel: "Oferta Santos7",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio retail S/ 159",
    tone: "#151515",
    image: "nike sabrina.jpeg"
  },
  {
    id: 28,
    name: "Polo Calvin Klein",
    category: "ropa",
    categoryLabel: "Polo · Calvin Klein",
    details: "Talla M",
    sizes: ["M"],
    price: 130,
    oldPrice: null,
    tag: "Original",
    tone: "#eeeeee",
    image: "polo calvin klein.jpeg"
  }
];

const newSneakers = [
  {
    id: 29,
    name: "Cosmic Runner (GS)",
    brand: "Nike",
    model: "Cosmic Runner (GS)",
    styleCode: "HM4002-400",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla EUR 36",
    sizeSystem: "EUR",
    sizes: ["36"],
    stock: 1,
    stockBySize: { "36": 1 },
    price: 129,
    referencePrice: 219.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/197863485607_1_20250326-mrtPeru.jpg"],
    image: "img1/197863485607_1_20250326-mrtPeru.jpg",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Descuento · 1 unidad",
    tone: "#e9edf0"
  },
  {
    id: 30,
    name: "Phantom GX Club TF",
    brand: "Nike",
    model: "Phantom GX Club TF",
    styleCode: "DD9486-446",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla EUR 42",
    sizeSystem: "EUR",
    sizes: ["42"],
    stock: 1,
    stockBySize: { "42": 1 },
    price: 159,
    referencePrice: 289.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/nike phantom.webp"],
    image: "img1/nike phantom.webp",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Descuento · 1 unidad",
    tone: "#e8edf1"
  },
  {
    id: 31,
    name: "Run Swift 2 (W)",
    brand: "Nike",
    model: "Run Swift 2 (W)",
    styleCode: "CU3528-004",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla EUR 37.5",
    sizeSystem: "EUR",
    sizes: ["37.5"],
    stock: 1,
    stockBySize: { "37.5": 1 },
    price: 215,
    referencePrice: 339.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/nike srum.jpg"],
    image: "img1/nike srum.jpg",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Descuento · 1 unidad",
    tone: "#e8e8e8"
  },
  {
    id: 32,
    name: "In-Season TR 13 (W)",
    brand: "Nike",
    model: "In-Season TR 13 (W)",
    styleCode: "DV3975-003",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla EUR 36.5",
    sizeSystem: "EUR",
    sizes: ["36.5"],
    stock: 1,
    stockBySize: { "36.5": 1 },
    price: 200,
    referencePrice: 349.90,
    referenceType: "label",
    referenceLabel: "Precio de etiqueta",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/nike sa.jpg"],
    image: "img1/nike sa.jpg",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Descuento · 1 unidad",
    tone: "#e9edf0"
  },
  {
    id: 33,
    name: "Legend 10 Club TF",
    brand: "Nike",
    model: "Legend 10 Club TF",
    styleCode: "DV4345-600",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Tallas EUR 43 y 44.5",
    sizeSystem: "EUR",
    sizes: ["43", "44.5"],
    stock: 2,
    stockBySize: { "43": 1, "44.5": 1 },
    price: 135,
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/tiempo legent.jpg"],
    image: "img1/tiempo legent.jpg",
    imageFit: "contain",
    tag: "Original",
    note: "Sin descuento · 2 unidades",
    tone: "#efedf0"
  },
  {
    id: 34,
    name: "Dunk Low Retro",
    brand: "Nike",
    model: "Dunk Low Retro",
    styleCode: "DV0833-401",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Tallas EUR 42.5 · 43 · 44",
    sizeSystem: "EUR",
    sizes: ["42.5", "43", "44"],
    stock: 3,
    stockBySize: { "42.5": 1, "43": 1, "44": 1 },
    price: 369.00,
    referencePrice: 459.90,
    referenceType: "label",
    referenceLabel: "Precio de etiqueta",
    referenceOnly: true,
    priceKind: "store",
    priceLabel: "S/ 369.00",
    availability: "in_stock",
    images: ["img1/dump.jpg"],
    image: "img1/dump.jpg",
    imageFit: "contain",
    tag: "Original",
    note: "Sin descuento · 3 unidades",
    tone: "#e9edf0"
  },
  {
    id: 35,
    name: "W Nike AL8",
    brand: "Nike",
    model: "W Nike AL8",
    styleCode: "FJ3794-600",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla EUR 36",
    sizeSystem: "EUR",
    sizes: ["36"],
    stock: 1,
    stockBySize: { "36": 1 },
    price: 399.90,
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/air max.webp"],
    image: "img1/air max.webp",
    imageFit: "contain",
    tag: "Original",
    note: "Sin descuento · precio de etiqueta S/ 399.90 · 1 unidad",
    tone: "#e9edf0"
  },
  {
    id: 36,
    name: "Air Max Nuaxis",
    brand: "Nike",
    model: "Air Max Nuaxis",
    styleCode: "FD4329-104",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla EUR 39",
    sizeSystem: "EUR",
    sizes: ["39"],
    stock: 1,
    stockBySize: { "39": 1 },
    price: 225,
    referencePrice: 329.90,
    referenceType: "label",
    referenceLabel: "Precio de etiqueta",
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/nike air max.webp"],
    image: "img1/nike air max.webp",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    saleLabel: "Oferta Santos7",
    note: "Oferta Santos7 · precio de etiqueta S/ 329.90 · 1 unidad",
    tone: "#e9edf0"
  },
  {
    id: 37,
    name: "Victori One Shower Slide (W)",
    brand: "Nike",
    model: "Victori One Shower Slide (W)",
    styleCode: "CZ7836-001",
    category: "calzado",
    subCategory: "sandalias",
    categoryLabel: "Sandalias · Nike",
    details: "Talla EUR 39",
    sizeSystem: "EUR",
    sizes: ["39"],
    stock: 1,
    stockBySize: { "39": 1 },
    price: 85,
    referencePrice: 149.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    saleLabel: "Oferta Santos7",
    availability: "in_stock",
    images: ["img1/image (1).png"],
    image: "img1/image (1).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Descuento · 1 unidad",
    tone: "#f1f1f1"
  },
  {
    id: 38,
    name: "Victori One Slide",
    brand: "Nike",
    model: "Victori One Slide",
    styleCode: "CN9675-401",
    category: "calzado",
    subCategory: "sandalias",
    categoryLabel: "Sandalias · Nike",
    details: "Talla EUR 40",
    sizeSystem: "EUR",
    sizes: ["40"],
    stock: 1,
    stockBySize: { "40": 1 },
    price: 100,
    referencePrice: 149.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    saleLabel: "Oferta Santos7",
    availability: "in_stock",
    images: ["img1/image (6).png"],
    image: "img1/image (6).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Descuento · 1 unidad",
    tone: "#e7ebef"
  },
  {
    id: 39,
    name: "Pacific LTR (W)",
    brand: "Nike",
    model: "Pacific LTR (W)",
    styleCode: "IQ4052-001",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla EUR 39",
    sizeSystem: "EUR",
    sizes: ["39"],
    stock: 2,
    stockBySize: { "39": 2 },
    price: 139,
    referencePrice: 319.90,
    referenceType: "label",
    referenceLabel: "Precio de etiqueta",
    referenceSource: "https://www.nike.com.pe/nike-pacific-ltr-zapatillas-para-ninos-grandes/iq4052-001/11100049006.html",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/image (3).png"],
    image: "img1/image (3).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Descuento · precio de etiqueta S/ 319.90 · 2 unidades EUR 39",
    tone: "#e9edf0"
  },
  {
    id: 40,
    name: "Air Jordan 1 Mid SE",
    brand: "Jordan",
    model: "Air Jordan 1 Mid SE",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Jordan",
    details: "Talla EUR 43",
    sizeSystem: "EUR",
    sizes: ["43"],
    stock: 1,
    stockBySize: { "43": 1 },
    price: 329,
    referencePrice: 599.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    saleLabel: "Oferta Santos7",
    availability: "in_stock",
    images: ["img1/Air Jordan 1 Mid.png"],
    image: "img1/Air Jordan 1 Mid.png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Descuento · 1 unidad",
    tone: "#e8ebee"
  },
  {
    id: 41,
    name: "Air Force 1 '07",
    brand: "Nike",
    model: "Air Force 1 '07",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla EUR 39",
    sizeSystem: "EUR",
    sizes: ["39"],
    stock: 1,
    stockBySize: { "39": 1 },
    price: 385,
    referencePrice: 549.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    referenceSource: "https://www.nike.com.pe/productos/calzado/af1",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/image (2).png", "img1/image (11).png"],
    image: "img1/image (2).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio Nike de referencia · 1 unidad",
    tone: "#efeee9"
  },
  {
    id: 43,
    name: "Palermo Moda Tongue Wns",
    brand: "Puma",
    model: "Palermo Moda Tongue Wns",
    styleCode: "401679-03",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Puma",
    details: "Talla EUR 36",
    sizeSystem: "EUR",
    sizes: ["36"],
    stock: 1,
    stockBySize: { "36": 1 },
    price: 159,
    referencePrice: 429.90,
    referenceType: "retail",
    referenceLabel: "Precio retail",
    referenceSource: "https://thn.pe/products/zapatillas-urbano-mujer-puma-palermo-moda-tongue-wns-401679-03",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/puma polermo.jpg"],
    image: "img1/puma polermo.jpg",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Descuento · 1 unidad",
    tone: "#e9e4d9"
  },
  {
    id: 44,
    name: "Puma-180",
    brand: "Puma",
    model: "Puma-180",
    styleCode: "389267-17",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Puma",
    details: "Talla EUR 37",
    sizeSystem: "EUR",
    sizes: ["37"],
    stock: 1,
    stockBySize: { "37": 1 },
    price: 199.90,
    referencePrice: 349.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    saleLabel: "Oferta Santos7",
    availability: "in_stock",
    images: ["img1/urbano-puma.jpg"],
    image: "img1/urbano-puma.jpg",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Descuento · 1 unidad",
    tone: "#ededed"
  },
  {
    id: 45,
    name: "RS-X Paisley Wns",
    brand: "Puma",
    model: "RS-X Paisley Wns",
    styleCode: "404649-01",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Puma",
    details: "Tallas EUR 35.5 y 37.5",
    sizeSystem: "EUR",
    sizes: ["35.5", "37.5"],
    stock: 1,
    stockBySize: null,
    price: 210,
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/zapatilla rs.png"],
    image: "img1/zapatilla rs.png",
    imageFit: "contain",
    tag: "Original",
    note: "Sin descuento · 1 unidad",
    tone: "#eee8e4"
  },
  {
    id: 47,
    name: "Puma Suede XL Jr",
    brand: "Puma",
    model: "Suede XL Jr",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Puma",
    details: "Talla EUR 40.5",
    sizeSystem: "EUR",
    sizes: ["40.5"],
    stock: 1,
    stockBySize: { "40.5": 1 },
    price: 399.90,
    styleCode: "397255-01",
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/Zapatillas Suede XL unisex.png"],
    image: "img1/Zapatillas Suede XL unisex.png",
    imageFit: "contain",
    tag: "Original",
    note: "Sin descuento · modelo y caja verificados · 1 unidad",
    tone: "#e9e9e9"
  },
  {
    id: 65,
    name: "JR. Mercurial Vapor 16 Academy",
    brand: "Nike",
    model: "JR. Mercurial Vapor 16 Academy",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla por confirmar",
    sizeSystem: "",
    sizes: [],
    stock: 1,
    stockBySize: null,
    price: 299.90,
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/chimpunes.jpg"],
    image: "img1/chimpunes.jpg",
    imageFit: "contain",
    tag: "Original",
    note: "Sin descuento · 1 unidad · talla por confirmar",
    tone: "#e9edf0"
  },
  {
    id: 66,
    name: "Tiempo Legend 9 Academy TF",
    brand: "Nike",
    model: "Tiempo Legend 9 Academy TF",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla por confirmar",
    sizeSystem: "",
    sizes: [],
    stock: 1,
    stockBySize: null,
    price: 199,
    referencePrice: 369.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "in_stock",
    images: ["img1/tiempo leguent.webp"],
    image: "img1/tiempo leguent.webp",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Descuento · 1 unidad · talla por confirmar",
    tone: "#e9edf0"
  }
];

const consultableProducts = [
  {
    id: 48,
    name: "Adidas Adilette azul",
    brand: "Adidas",
    model: "Adilette",
    category: "calzado",
    subCategory: "sandalias",
    categoryLabel: "Sandalias · Adidas",
    details: "Talla EUR 39",
    sizeSystem: "EUR",
    sizes: ["39"],
    stock: null,
    stockBySize: null,
    price: 95,
    referencePrice: 129,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    referenceSource: "https://www.adidas.pe/sandalias-adilette/288022.html",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (5).png"],
    image: "img1/image (5).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio adidas de referencia · talla EUR 39",
    tone: "#e8ecef"
  },
  {
    id: 49,
    name: "Nike Victori One Shower Slide",
    brand: "Nike",
    model: "Victori One Shower Slide",
    category: "calzado",
    subCategory: "sandalias",
    categoryLabel: "Sandalias · Nike",
    details: "Talla por confirmar",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 85,
    referencePrice: 149.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    referenceSource: "https://www.nike.com.pe/nike-victori-one-sandalias-de-ducha-para-mujer/cz7836-001/10696713011.html",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (7).png"],
    image: "img1/image (7).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio Nike de referencia · talla por confirmar",
    tone: "#e9e9e9"
  },
  {
    id: 50,
    name: "Fila Drifter Basic",
    brand: "Fila",
    model: "Drifter Basic",
    category: "calzado",
    subCategory: "sandalias",
    categoryLabel: "Sandalias · Fila",
    details: "Talla por confirmar",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 60,
    referencePrice: 119.90,
    referenceType: "retail",
    referenceLabel: "Precio retail",
    referenceSource: "https://platanitos.com/pe/producto/fila-sandalia-hombre-ojota-drifter-basic-blanco-fdw620r8edqd",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (10).png"],
    image: "img1/image (10).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio retail de referencia · talla por confirmar",
    tone: "#f0f0f0"
  },
  {
    id: 51,
    name: "Nike Air Max Dn",
    brand: "Nike",
    model: "Air Max Dn",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla por confirmar",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 400,
    referencePrice: 759.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    referenceSource: "https://www.nike.com.pe/nike-air-max-dn-zapatillas-para-hombre/dv3337-016/11019364016.html",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (9).png"],
    image: "img1/image (9).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio Nike de referencia · talla por confirmar",
    tone: "#edf0f1"
  },
  {
    id: 52,
    name: "Puma Leadcat 2.0",
    brand: "Puma",
    model: "Leadcat 2.0",
    category: "calzado",
    subCategory: "sandalias",
    categoryLabel: "Sandalias · Puma",
    details: "Tallas EUR 40.5 y 42",
    sizes: ["40.5", "42"],
    stock: null,
    stockBySize: null,
    price: 85,
    referencePrice: 119.90,
    referenceType: "market-reference",
    referenceLabel: "Precio referencial",
    referenceSource: "https://pe.puma.com/pd/sandalias-leadcat-2.0/384139.html",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (8).png"],
    image: "img1/image (8).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio PUMA de referencia · disponibilidad por confirmar",
    tone: "#e9e9e9"
  },
  {
    id: 53,
    name: "Fila Drifter Basic negro/rojo",
    brand: "Fila",
    model: "Drifter Basic negro/rojo",
    category: "calzado",
    subCategory: "sandalias",
    categoryLabel: "Sandalias · Fila",
    details: "Tallas EUR 43, 44.5 y 46",
    sizes: ["43", "44.5", "46"],
    stock: null,
    stockBySize: null,
    price: 60,
    referencePrice: 119.90,
    referenceType: "retail",
    referenceLabel: "Precio retail",
    referenceSource: "https://platanitos.com/pe/producto/fila-sandalia-hombre-ojota-drifter-basic-blanco-fdw620r8edqd",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (21).png"],
    image: "img1/image (21).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio retail de referencia · disponibilidad por confirmar",
    tone: "#e9e9e9"
  },
  {
    id: 54,
    name: "Nike Victori One Slide",
    brand: "Nike",
    model: "Victori One Slide",
    category: "calzado",
    subCategory: "sandalias",
    categoryLabel: "Sandalias · Nike",
    details: "Talla por confirmar",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 100,
    referencePrice: 149.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    referenceSource: "https://www.nike.com.pe/nike-victori-one-sandalia-para-mujer/cn9677-011/11099076011.html",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/sandalia Nike tipo slide.png"],
    image: "img1/sandalia Nike tipo slide.png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio Nike de referencia · talla por confirmar",
    tone: "#e4e8ee"
  },
  {
    id: 55,
    name: "Pack x3 polos New Balance",
    brand: "New Balance",
    model: "Pack x3 polos",
    category: "ropa",
    subCategory: "polos",
    categoryLabel: "Polos · New Balance",
    details: "Talla por confirmar · pack de 3",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 99,
    referencePrice: 149,
    referenceType: "market-reference",
    referenceLabel: "Precio referencial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (12).png"],
    image: "img1/image (12).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Pack de 3 · talla por confirmar",
    tone: "#f0f0f0"
  },
  {
    id: 56,
    name: "Jordan Flight Modal · pack x2",
    brand: "Jordan",
    model: "Flight Modal · pack x2",
    category: "ropa",
    subCategory: "polos",
    categoryLabel: "Polos · Jordan",
    details: "Talla M · pack de 2",
    sizes: ["M"],
    stock: null,
    stockBySize: null,
    price: 100,
    referencePrice: 199.90,
    referenceType: "market-reference",
    referenceLabel: "Precio referencial",
    referenceSource: "https://www.nike.com/t/jordan-mens-modal-undershirt-2-pack-XymUidhO",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (13).png"],
    image: "img1/image (13).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Pack de 2 · talla M · precio referencial",
    tone: "#e5e5e5"
  },
  {
    id: 57,
    name: "Gorra Nike gris",
    brand: "Nike",
    model: "Gorra gris",
    category: "accesorios",
    subCategory: "gorras",
    categoryLabel: "Gorras · Nike",
    details: "Talla M/L",
    sizes: ["M/L"],
    stock: null,
    stockBySize: null,
    price: 85,
    referencePrice: 99.90,
    referenceType: "market-reference",
    referenceLabel: "Precio referencial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (14).png"],
    image: "img1/image (14).png",
    imageFit: "cover",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio Nike de referencia · disponibilidad por confirmar",
    tone: "#e8e8e8"
  },
  {
    id: 58,
    name: "Gorra BMW Motorsport",
    brand: "BMW",
    model: "Motorsport",
    category: "accesorios",
    subCategory: "gorras",
    categoryLabel: "Gorras · BMW",
    details: "Talla única",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 100,
    referencePrice: 129.90,
    referenceType: "market-reference",
    referenceLabel: "Precio referencial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (15).png"],
    image: "img1/image (15).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Talla única · precio referencial de mercado",
    tone: "#f0f0f0"
  },
  {
    id: 59,
    name: "Gorra Guess monogram",
    brand: "Guess",
    model: "Monogram",
    category: "accesorios",
    subCategory: "gorras",
    categoryLabel: "Gorras · Guess",
    details: "Talla única",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 100,
    referencePrice: 135,
    referenceType: "market-reference",
    referenceLabel: "Precio referencial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (16).png"],
    image: "img1/image (16).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Talla única · precio referencial de mercado",
    tone: "#e7e3de"
  },
  {
    id: 60,
    name: "Gorra Guess negra",
    brand: "Guess",
    model: "Gorra negra",
    category: "accesorios",
    subCategory: "gorras",
    categoryLabel: "Gorras · Guess",
    details: "Talla única",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 135,
    referencePrice: 179.90,
    referenceType: "market-reference",
    referenceLabel: "Precio referencial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (17).png"],
    image: "img1/image (17).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Talla única · precio referencial de mercado",
    tone: "#e9e9e9"
  },
  {
    id: 61,
    name: "Gorra Nike blanca",
    brand: "Nike",
    model: "Gorra blanca",
    category: "accesorios",
    subCategory: "gorras",
    categoryLabel: "Gorras · Nike",
    details: "Talla única",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 90,
    referencePrice: 99.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    referenceSource: "https://www.nike.com.pe/gorra-sportswear-heritage-86/943092-010/10244929001.html",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (18).png"],
    image: "img1/image (18).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio Nike de referencia · talla única",
    tone: "#f0f0f0"
  },
  {
    id: 62,
    name: "Gorra Tommy Hilfiger beige",
    brand: "Tommy Hilfiger",
    model: "Gorra beige",
    category: "accesorios",
    subCategory: "gorras",
    categoryLabel: "Gorras · Tommy Hilfiger",
    details: "Talla única",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 135,
    referencePrice: 169.90,
    referenceType: "market-reference",
    referenceLabel: "Precio referencial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (19).png"],
    image: "img1/image (19).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Talla única · precio referencial de mercado",
    tone: "#eee5d9"
  },
  {
    id: 63,
    name: "Polo Puma F1",
    brand: "Puma",
    model: "F1 Essentials Logo",
    category: "ropa",
    subCategory: "polos",
    categoryLabel: "Polos · Puma F1",
    details: "Talla S",
    sizes: ["S"],
    stock: null,
    stockBySize: null,
    price: 70,
    referencePrice: 99,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    referenceSource: "https://pe.puma.com/pd/polo-f1-essentials-logo-para-hombre/633264.html",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (22).png"],
    image: "img1/image (22).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Precio PUMA de referencia · disponibilidad por confirmar",
    tone: "#f0f0f0"
  },
  {
    id: 64,
    name: "Mochila Kobe / FCB",
    brand: "Nike",
    model: "Kobe / FCB",
    category: "accesorios",
    subCategory: "mochilas",
    categoryLabel: "Mochilas · Nike",
    details: "Medidas por confirmar",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 100,
    referencePrice: 179.90,
    referenceType: "market-reference",
    referenceLabel: "Precio referencial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["img1/image (23).png"],
    image: "img1/image (23).png",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Medidas por confirmar · precio referencial de mercado",
    tone: "#e9e9e9"
  }
];

const latestProducts = [
  {
    id: 69,
    name: "Mochila Air Jordan",
    brand: "Jordan",
    model: "Mochila Air Jordan",
    category: "accesorios",
    subCategory: "mochilas",
    categoryLabel: "Mochilas · Air Jordan",
    details: "2 unidades disponibles",
    sizes: [],
    stock: 2,
    stockBySize: null,
    price: 129,
    priceKind: "store",
    availability: "in_stock",
    images: ["mochila air jordan.jpeg"],
    image: "mochila air jordan.jpeg",
    imageFit: "contain",
    tag: "Stock limitado",
    tagClass: "tag-sale",
    note: "Solo 2 unidades",
    tone: "#e9edf0"
  },
  {
    id: 70,
    name: "Nike Ava Rover PRM",
    brand: "Nike",
    model: "Ava Rover PRM",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla EUR 42 · box cortado",
    sizeSystem: "EUR",
    sizes: ["42"],
    stock: 1,
    stockBySize: { "42": 1 },
    price: 299,
    priceKind: "store",
    availability: "in_stock",
    images: ["new ava rover prm.jpeg"],
    image: "new ava rover prm.jpeg",
    imageFit: "contain",
    tag: "Pago completo",
    note: "Box cortado · 1 unidad",
    tone: "#e8edf1"
  },
  {
    id: 71,
    name: "Air Jordan 1 Retro High OG",
    brand: "Jordan",
    model: "Air Jordan 1 Retro High OG",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Jordan",
    details: "Talla EUR 39 · box cortado",
    sizeSystem: "EUR",
    sizes: ["39"],
    stock: 1,
    stockBySize: { "39": 1 },
    price: 359,
    priceKind: "store",
    availability: "in_stock",
    images: ["air jordan 1 retro high og.jpeg"],
    image: "air jordan 1 retro high og.jpeg",
    imageFit: "contain",
    tag: "Yape completo",
    note: "Box cortado · 1 unidad",
    tone: "#e9edf0"
  },
  {
    id: 72,
    name: "Polera Puma BMW",
    brand: "Puma",
    model: "BMW Motorsport",
    category: "ropa",
    subCategory: "poleras",
    categoryLabel: "Poleras · Puma BMW",
    details: "Tallas M · L · XL",
    sizes: ["M", "L", "XL"],
    stock: null,
    stockBySize: null,
    price: 110,
    priceKind: "store",
    availability: "inquiry",
    images: ["polera puma bmw.jpeg"],
    image: "polera puma bmw.jpeg",
    imageFit: "contain",
    tag: "Últimas unidades",
    tagClass: "tag-sale",
    note: "Últimas unidades · tallas M, L y XL",
    tone: "#eeeeec"
  },
  {
    id: 73,
    name: "Polo Jordan 💎",
    brand: "Jordan",
    model: "Jordan Polo Jumpman bordado",
    styleCode: "IF5566-010",
    category: "ropa",
    subCategory: "polos",
    categoryLabel: "Polos · Jordan",
    details: "Talla S",
    sizes: ["S"],
    stock: null,
    stockBySize: null,
    price: 100,
    referencePrice: 119.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "in_stock",
    images: ["polo air jordan.jpeg"],
    image: "polo air jordan.jpeg",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Polo Jordan 💎 · talla S",
    tone: "#eeeeec"
  },
  {
    id: 74,
    name: "Nike Moto 2K",
    brand: "Nike",
    model: "Moto 2K",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla EUR 40 · box cortado",
    sizeSystem: "EUR",
    sizes: ["40"],
    stock: 1,
    stockBySize: { "40": 1 },
    price: 319,
    priceKind: "store",
    availability: "in_stock",
    images: ["nike moto 2k.jpeg"],
    image: "nike moto 2k.jpeg",
    imageFit: "contain",
    tag: "Box cortado",
    note: "Box cortado · 1 unidad",
    tone: "#e8edf1"
  },
  {
    id: 75,
    name: "GUESS Logo Tee",
    brand: "GUESS",
    model: "GUESS Logo Tee",
    category: "ropa",
    subCategory: "polos",
    categoryLabel: "Polos · GUESS",
    details: "Tallas S · L",
    sizes: ["S", "L"],
    stock: null,
    stockBySize: null,
    price: 100,
    referencePrice: 190,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "in_stock",
    images: ["POLO GUESS.jpeg"],
    image: "POLO GUESS.jpeg",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Tallas S y L",
    tone: "#eeeeec"
  },
  {
    id: 76,
    name: "GUESS Side Panel Shorts",
    brand: "GUESS",
    model: "GUESS Side Panel Shorts",
    category: "ropa",
    subCategory: "shorts",
    categoryLabel: "Shorts · GUESS",
    details: "Talla M",
    sizes: ["M"],
    stock: null,
    stockBySize: null,
    price: 115,
    priceKind: "store",
    availability: "in_stock",
    images: ["SHORT GUESS.jpeg"],
    image: "SHORT GUESS.jpeg",
    imageFit: "contain",
    tag: "Original",
    note: "Talla M",
    tone: "#e9e9e7"
  },
  {
    id: 77,
    name: "Jordan Graphic Tee",
    brand: "Jordan",
    model: "Jordan Graphic Tee",
    category: "ropa",
    subCategory: "polos",
    categoryLabel: "Polos · Jordan",
    details: "Tallas M · L",
    sizes: ["M", "L"],
    stock: null,
    stockBySize: null,
    price: 120,
    referencePrice: 159.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "in_stock",
    images: ["POLO JORDAN.jpeg"],
    image: "POLO JORDAN.jpeg",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Tallas M y L",
    tone: "#eeeeec"
  },
  {
    id: 78,
    name: "Nike Elemental Backpack 21L",
    brand: "Nike",
    model: "Elemental Backpack 21L",
    category: "accesorios",
    subCategory: "mochilas",
    categoryLabel: "Mochilas · Nike",
    details: "Sin talla",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 119,
    referencePrice: 169.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "in_stock",
    images: ["MOCHILA NIKE.jpeg"],
    image: "MOCHILA NIKE.jpeg",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "21 L · sin talla",
    tone: "#eeeeec"
  },
  {
    id: 79,
    name: "GUESS Tape Tee",
    brand: "GUESS",
    model: "GUESS Tape Tee",
    category: "ropa",
    subCategory: "polos",
    categoryLabel: "Polos · GUESS",
    details: "Talla S",
    sizes: ["S"],
    stock: null,
    stockBySize: null,
    price: 100,
    referencePrice: 190,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "in_stock",
    images: ["POLO GUESS TALLA S.jpeg"],
    image: "POLO GUESS TALLA S.jpeg",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Talla S",
    tone: "#eeeeec"
  },
  {
    id: 80,
    name: "Nike Heritage Backpack 21L “Just Do It”",
    brand: "Nike",
    model: "Heritage Backpack 21L “Just Do It”",
    category: "accesorios",
    subCategory: "mochilas",
    categoryLabel: "Mochilas · Nike",
    details: "Sin talla",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 119,
    referencePrice: 159.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "in_stock",
    images: ["MOCHILA NIKE 21 L.jpeg"],
    image: "MOCHILA NIKE 21 L.jpeg",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "21 L · sin talla",
    tone: "#eeeeec"
  },
  {
    id: 81,
    name: "Nike Air Max INTRLK Lite",
    brand: "Nike",
    model: "Air Max INTRLK Lite",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla EUR 39",
    sizeSystem: "EUR",
    sizes: ["39"],
    stock: null,
    stockBySize: null,
    price: 219,
    referencePrice: 739.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "in_stock",
    images: ["NIKE AIR MAX INTRLK LITE.jpeg"],
    image: "NIKE AIR MAX INTRLK LITE.jpeg",
    imageFit: "contain",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: null,
    tone: "#e8edf1"
  }
];

const incomingProducts = [
  {
    id: 82,
    name: "Short Puma Deportivo",
    brand: "Puma",
    model: "Puma Essentials No.1 Logo Shorts",
    styleCode: "682594_01",
    category: "ropa",
    subCategory: "shorts",
    categoryLabel: "Shorts · Puma",
    details: "Talla M",
    sizes: ["M"],
    stock: 1,
    stockBySize: { "M": 1 },
    price: 65,
    referencePrice: 89,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "in_stock",
    images: ["ZAPA3.jpeg"],
    image: "ZAPA3.jpeg",
    imageFit: "cover",
    tag: "Oferta Santos7",
    tagClass: "tag-sale",
    note: "Short Puma Deportivo · talla M",
    tone: "#e7e8e8"
  },
  {
    id: 83,
    name: "Nike P-6000 GS",
    brand: "Nike",
    model: "Nike P-6000",
    styleCode: "CD6404-106",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Nike",
    details: "Talla EUR 38.5 · box cortado",
    sizeSystem: "EUR",
    sizes: ["38.5"],
    stock: 1,
    stockBySize: { "38.5": 1 },
    price: 289.90,
    referencePrice: 549.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "in_stock",
    images: ["ZAPA4.jpeg"],
    image: "ZAPA4.jpeg",
    imageFit: "contain",
    tag: "Box cortado",
    tagClass: "tag-sale",
    note: "BOX CORTADO · 1 unidad",
    tone: "#e8e5e1"
  },
  {
    id: 84,
    name: "Short Jordan Oversize",
    brand: "Jordan",
    model: "Jordan Dri-FIT Sport Diamond Shorts",
    styleCode: "DQ7334-405",
    category: "ropa",
    subCategory: "shorts",
    categoryLabel: "Shorts · Jordan",
    details: "Talla L",
    sizes: ["L"],
    stock: 1,
    stockBySize: { "L": 1 },
    price: 130,
    referencePrice: 199.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    saleLabel: "Última 🚨",
    priceKind: "store",
    availability: "in_stock",
    images: ["SHORT.jpeg"],
    image: "SHORT.jpeg",
    imageFit: "contain",
    tag: "Última 🚨",
    tagClass: "tag-sale",
    note: "ÚLTIMA 🚨 · talla L",
    tone: "#e9e4de"
  },
  {
    id: 85,
    name: "Air Jordan 1 Low",
    brand: "Jordan",
    model: "Air Jordan 1 Low Retro",
    styleCode: "553558-141",
    category: "calzado",
    subCategory: "zapatillas",
    categoryLabel: "Zapatillas · Jordan",
    details: "Talla por confirmar · box cortado",
    sizeSystem: "EUR",
    sizes: [],
    stock: null,
    stockBySize: null,
    price: 339,
    referencePrice: 579.90,
    referenceType: "official",
    referenceLabel: "Precio oficial",
    saleLabel: "Oferta Santos7",
    priceKind: "store",
    availability: "inquiry",
    images: ["ZAPA.jpeg", "ZAPA2.jpeg"],
    image: "ZAPA.jpeg",
    imageFit: "contain",
    tag: "Box cortado",
    tagClass: "tag-sale",
    note: "BOX CORTADO · talla por confirmar",
    tone: "#e8e8e8"
  }
];

// La grabación confirmó estas referencias como repetidas o con precio/datos
// incorrectos. Se conservan sus imágenes y objetos de origen, pero no se
// muestran como stock activo hasta volver a confirmarlos.
const removedProductIds = new Set([2, 8, 35, 47, 49, 54, 58, 59, 65]);

// Las capturas AREGLO 3, 4, 5, 8 y 12 confirman estos cuatro agotados.
// Se fuerza el estado aquí para que siempre aparezcan en la sección Agotados,
// aunque una ficha antigua conserve precio o disponibilidad anterior.
const confirmedSoldOutProductIds = new Set([7, 9, 10, 12]);

export const products = [...latestProducts, ...incomingProducts, ...existingProducts, ...newSneakers, ...consultableProducts]
  .map((product) => confirmedSoldOutProductIds.has(product.id)
    ? { ...product, stock: 0, stockBySize: null, availability: "out_of_stock" }
    : product)
  .filter((product) => !removedProductIds.has(product.id))
  .filter((product) => (Array.isArray(product.images) && product.images.length > 0) || Boolean(product.image));
